### ISSUE TITLE
Convertion to Matplotlib to Shape file format

### ISSUE THREAD

**Issue by Inusha5920** [thusharabandara/Geo-Area-Calculator-and-Map-Creation-Tool#1]
Dear sir, 
In our project, we want to create the shape through Matplolib using absolute coordinates. 
We want to convert that Matplotlib to Shape file format to support Arc GIS. We are trying to figure out this issue using pyshp. 
But still we hard to find the solution. We need your guidance to solve this issue.

**Comment by thusharabandara** [comment]
Push all your work to the GitHub remote repository.
